<?php 

/* ------- Check ACF -------- */ 
add_action( 'acf/init', 'checkACFtheme' );

function checkACFtheme() {

	// Add theme options

	acf_add_options_page(array(
		'page_title'  => 'Theme General Settings',
		'menu_title'  => 'Theme Settings',
		'menu_slug'   => 'theme-general-settings',
		'capability'  => 'edit_posts',
		'redirect'    => false
	));

	acf_add_options_sub_page(array(
		'page_title'  => 'Theme Typography Settings',
		'menu_title'  => 'Typography',
		'parent_slug' => 'theme-general-settings',
	));

	acf_add_options_sub_page(array(
		'page_title'  => 'Post Types',
		'menu_title'  => 'Post Types',
		'parent_slug' => 'theme-general-settings',
	));
	


	// Change Site Title, Descriptions and Email 

	add_action('acf/init', 'siteDetails'); 
	add_action('acf/init', 'dynamic_style'); 

	function siteDetails() {

		$sitetitle = get_field('site_title', 'option');   

		if ($sitetitle) {
			update_option('blogname', $sitetitle);
		} else {
			update_option( 'blogname', '' );  
		}

		$tagline = get_field('tagline', 'option');    

		if ($tagline) {
			update_option('blogdescription', $tagline);
		} else {
			update_option( 'blogdescription', '' ); 
		}

		$adminemail = get_field('admin_email', 'option');   

			if ($adminemail) {
				update_option('admin_email', $adminemail);
			} else {
				update_option( 'admin_email', '' ); 
			}

	}

	// Custom post types 

	function create_posttype() {

		if( have_rows('post_type', 'option') ):

			while( have_rows('post_type','option') ) : the_row();

				$labels = array(
					'name'                => __( get_sub_field('pt_name','options') ),
					'singular_name'       => __( get_sub_field('pt_singular','options') ),
					'menu_name'           => __( get_sub_field('pt_name','options') ),
					'parent_item_colon'   => __( 'Parent ' . get_sub_field('pt_singular','options') ),
					'all_items'           => __( 'All ' . get_sub_field('pt_name','options') ),
					'view_item'           => __( 'View ' . get_sub_field('pt_singular','options') ),
					'add_new_item'        => __( 'Add New ' . get_sub_field('pt_singular','options') ),
					'add_new'             => __( 'Add New ' . get_sub_field('pt_singular','options') ),
					'edit_item'           => __( 'Edit ' . get_sub_field('pt_singular','options') ),
					'update_item'         => __( 'Update ' . get_sub_field('pt_singular','options') ),
					'search_items'        => __( 'Search ' . get_sub_field('pt_singular','options') ),
					'not_found'           => __( 'Not Found' ),
					'not_found_in_trash'  => __( 'Not found in Trash' ),
				);

				$args = array(
					'label'               => __( get_sub_field('pt_slug','options') ),
					'labels'              => $labels,
					'supports'            => array( 'title', 'excerpt', 'author', 'editor', 'comments', 'thumbnail', 'revisions', ),
					'taxonomies'          => array( 'category', 'post_tag' ),
					'hierarchical'        => false,
					'public'              => true,
					'show_ui'             => true,
					'show_in_menu'        => true,
					'show_in_nav_menus'   => true,
					'show_in_admin_bar'   => true,
					'menu_position'       => 5,
					'can_export'          => true,
					'has_archive'         => ( get_sub_field('pt_archive','options') ),
					'exclude_from_search' => ( get_sub_field('pt_search','options') ),
					'publicly_queryable'  => ( get_sub_field('pt_public','options') ),
					'capability_type'     => 'post',
					'show_in_rest' => true,
					'menu_icon' => ( get_sub_field('pt_icon','options') ),
				);

				register_post_type( get_sub_field('pt_slug','options'), $args );

			endwhile;

		endif;

	}
	
	add_action( 'init', 'create_posttype' );

	// Add favicion link to <head>

	function add_favicon(){ ?>

		<link rel="icon" type="image/png" href="<?php echo the_field('favicon', 'option'); ?>">
		<link rel="shortcut icon" type="image/png" href="<?php echo the_field('favicon', 'option'); ?>">
		<link rel="apple-touch-icon" type="image/png" href="<?php echo the_field('favicon', 'option'); ?>">
		<link rel="apple-touch-icon-precomposed" type="image/png" href="<?php echo the_field('favicon', 'option'); ?>">

	<?php }

	add_action('wp_head','add_favicon');

// Check ACF END
};

function my_acf_add_local_field_groups() {

	if ( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_63da53f34d63f',
		'title' => 'Post Types',
		'fields' => array(
			array(
				'key' => 'field_63da53f3ac38b',
				'label' => 'Post Type',
				'name' => 'post_type',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Post Type',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_63da543bac38c',
						'label' => 'Plural Name (e.g. Events)',
						'name' => 'pt_name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_63da53f3ac38b',
					),
					array(
						'key' => 'field_63da86785e723',
						'label' => 'Singular Name (e.g. Event)',
						'name' => 'pt_singular',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_63da53f3ac38b',
					),
					array(
						'key' => 'field_63da549fac38d',
						'label' => 'Slug',
						'name' => 'pt_slug',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'Lower case with no spaces (e.g. meet-the-team). If the posts have an archive, this will be the slug used (e.g. domain.com/meet-the-team).',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_63da53f3ac38b',
					),
					array(
						'key' => 'field_63da5545ac38e',
						'label' => 'Public',
						'name' => 'pt_public',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Do posts need their own page and permalink?',
						'default_value' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
						'parent_repeater' => 'field_63da53f3ac38b',
					),
					array(
						'key' => 'field_63da57466c93e',
						'label' => 'Archive',
						'name' => 'pt_archive',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Does posts need an archive?',
						'default_value' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
						'parent_repeater' => 'field_63da53f3ac38b',
					),
					array(
						'key' => 'field_63da580d481c2',
						'label' => 'Search',
						'name' => 'pt_search',
						'aria-label' => '',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Do you want to show posts in search results?',
						'default_value' => 0,
						'ui_on_text' => '',
						'ui_off_text' => '',
						'ui' => 1,
						'parent_repeater' => 'field_63da53f3ac38b',
					),
					array(
						'key' => 'field_63da5875481c3',
						'label' => 'Icon',
						'name' => 'pt_icon',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'Copy and paste class name from <a href="https://developer.wordpress.org/resource/dashicons">Dashicons</a> (e.g. dashicon-airplane).',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_63da53f3ac38b',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-post-types',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	endif;

	if ( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_62e7b41297b52',
		'title' => 'Details',
		'fields' => array(
			array(
				'key' => 'field_62e3b113a5bab',
				'label' => 'Site Title',
				'name' => 'site_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62e3b239043f5',
				'label' => 'Site Tagline',
				'name' => 'tagline',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62e7b44addb54',
				'label' => 'Address',
				'name' => 'address',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_62e7b45f5e567',
				'label' => 'Phone',
				'name' => 'phone',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62e7b47837256',
				'label' => 'Email Address',
				'name' => 'email_address',
				'aria-label' => '',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	endif;

	if ( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_62c7f0c96e85d',
		'title' => 'Body',
		'fields' => array(
			array(
				'key' => 'field_63d298ec22c74',
				'label' => 'Body Font',
				'name' => 'body_font',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Arial',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d29c0659a24',
				'label' => 'Body Font Size',
				'name' => 'body_size',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 16,
				'min' => 12,
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => 'px',
			),
			array(
				'key' => 'field_63d28ff822ae9',
				'label' => 'Body Font Weight',
				'name' => 'body_weight',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					100 => '100',
					200 => '200',
					300 => '300',
					400 => '400',
					500 => '500',
					600 => '600',
					700 => '700',
					800 => '800',
					900 => '900',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62c7f154ff3b9',
				'label' => 'Colour',
				'name' => 'body_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-typography',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	endif;

	if ( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_62e3b0ef329e9',
		'title' => 'Logo',
		'fields' => array(
			array(
				'key' => 'field_6353fdc72fc3e',
				'label' => 'White Logo',
				'name' => 'white_logo',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => 'For use on dark backgrounds',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'thumbnail',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	endif;

	if ( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_62e7b2a64acc9',
		'title' => 'Brand Colours',
		'fields' => array(
			array(
				'key' => 'field_62e7b2b662265',
				'label' => 'Primary Colour',
				'name' => 'primary_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e7b2fb62266',
				'label' => 'Second Colour',
				'name' => 'second_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e7b31462267',
				'label' => 'Third Colour',
				'name' => 'third_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e7b33b62268',
				'label' => 'Dark Colour',
				'name' => 'dark_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => 'Should be same as primary brand colour if legible. Needs to work with white text overlaid.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62ea3e6c4db39',
				'label' => 'Light Colour',
				'name' => 'light_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => 'Used for tinted backgrounds. Should be approx 0.1 (10%) to 0.15 (15%) of brand colour.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'enable_opacity' => 1,
				'return_format' => 'string',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 2,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	endif;

	if ( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_62e7e8ce45432',
		'title' => 'Links',
		'fields' => array(
			array(
				'key' => 'field_62e7e8f01e736',
				'label' => 'Link Weight',
				'name' => 'link_weight',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					100 => '100',
					200 => '200',
					300 => '300',
					400 => '400',
					500 => '500',
					600 => '600',
					700 => '700',
					800 => '800',
					900 => '900',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63d2965aea5ed',
				'label' => 'Link Style',
				'name' => 'link_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'normal' => 'normal',
					'italic' => 'italic',
				),
				'default_value' => 'normal',
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62e7e8ce50c39',
				'label' => 'Colour',
				'name' => 'link_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e80130b972b',
				'label' => 'Hover Colour',
				'name' => 'link_hover_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-typography',
				),
			),
		),
		'menu_order' => 2,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	endif;

	if ( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_62e7aec4d5695',
		'title' => 'Headings',
		'fields' => array(
			array(
				'key' => 'field_62e7aec4e1e81',
				'label' => 'H1 Font',
				'name' => 'h1_font',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2914bf2e59',
				'label' => 'H1 Font Weight',
				'name' => 'h1_font_weight',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					100 => '100',
					200 => '200',
					300 => '300',
					400 => '400',
					500 => '500',
					600 => '600',
					700 => '700',
					800 => '800',
					900 => '900',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63d2af211c752',
				'label' => 'H1 Font Size (Desktop)',
				'name' => 'h1_font_size_desktop',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => 'px',
			),
			array(
				'key' => 'field_63d2b0471c75d',
				'label' => 'H1 Font Size (Mobile)',
				'name' => 'h1_font_size_mobile',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => 'px',
			),
			array(
				'key' => 'field_63d2947ef2e5f',
				'label' => 'H1 Style',
				'name' => 'h1_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'normal' => 'normal',
					'italic' => 'italic',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62e7aec4e1ec4',
				'label' => 'H1 Colour',
				'name' => 'h1_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e7aefeb325d',
				'label' => 'H2 Font',
				'name' => 'h2_font',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2916bf2e5a',
				'label' => 'H2 Font Weight',
				'name' => 'h2_font_weight',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					100 => '100',
					200 => '200',
					300 => '300',
					400 => '400',
					500 => '500',
					600 => '600',
					700 => '700',
					800 => '800',
					900 => '900',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63d2af6b1c753',
				'label' => 'H2 Font Size (Desktop)',
				'name' => 'h2_font_size_desktop',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2b03b1c75c',
				'label' => 'H2 Font Size (Mobile)',
				'name' => 'h2_font_size_mobile',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d295aaf2e61',
				'label' => 'H2 Style',
				'name' => 'h2_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'normal' => 'normal',
					'italic' => 'italic',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62e7aefeb3291',
				'label' => 'H2 Colour',
				'name' => 'h2_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e7afb98be9e',
				'label' => 'H3 Font',
				'name' => 'h3_font',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d293a4f2e5b',
				'label' => 'H3 Font Weight',
				'name' => 'h3_font_weight',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					100 => '100',
					200 => '200',
					300 => '300',
					400 => '400',
					500 => '500',
					600 => '600',
					700 => '700',
					800 => '800',
					900 => '900',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63d2af7b1c754',
				'label' => 'H3 Font Size (Desktop)',
				'name' => 'h3_font_size_desktop',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2b02c1c75b',
				'label' => 'H3 Font Size (Mobile)',
				'name' => 'h3_font_size_mobile',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2958bf2e60',
				'label' => 'H3 Style',
				'name' => 'h3_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'normal' => 'normal',
					'italic' => 'italic',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62e7afb98bee3',
				'label' => 'H3 Colour',
				'name' => 'h3_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e7aff3e6cac',
				'label' => 'H4 Font',
				'name' => 'h4_font',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d293edf2e5c',
				'label' => 'H4 Font Weight',
				'name' => 'h4_font_weight',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					100 => '100',
					200 => '200',
					300 => '300',
					400 => '400',
					500 => '500',
					600 => '600',
					700 => '700',
					800 => '800',
					900 => '900',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63d2af891c755',
				'label' => 'H4 Font Size (Desktop)',
				'name' => 'h4_font_size_desktop',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2b0191c75a',
				'label' => 'H4 Font Size (Mobile)',
				'name' => 'h4_font_size_mobile',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d295bef2e62',
				'label' => 'H4 Style',
				'name' => 'h4_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'normal' => 'normal',
					'italic' => 'italic',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62e7aff3e6cfc',
				'label' => 'H4 Colour',
				'name' => 'h4_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e7b0142d5cc',
				'label' => 'H5 Font',
				'name' => 'h5_font',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2940cf2e5d',
				'label' => 'H5 Font Weight',
				'name' => 'h5_font_weight',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					100 => '100',
					200 => '200',
					300 => '300',
					400 => '400',
					500 => '500',
					600 => '600',
					700 => '700',
					800 => '800',
					900 => '900',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63d2afa11c756',
				'label' => 'H5 Font Size (Desktop)',
				'name' => 'h5_font_size_desktop',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2b00c1c759',
				'label' => 'H5 Font Size (Mobile)',
				'name' => 'h6_font_size_mobile',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d295d0f2e63',
				'label' => 'H5 Style',
				'name' => 'h5_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'normal' => 'normal',
					'italic' => 'italic',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62e7b0142d5f4',
				'label' => 'H5 Colour',
				'name' => 'h5_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_62e7b02d7eb0c',
				'label' => 'H6 Font',
				'name' => 'h6_font',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d29462f2e5e',
				'label' => 'H6 Font Weight',
				'name' => 'h6_font_weight',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					100 => '100',
					200 => '200',
					300 => '300',
					400 => '400',
					500 => '500',
					600 => '600',
					700 => '700',
					800 => '800',
					900 => '900',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63d2afad1c757',
				'label' => 'H6 Font Size (Desktop)',
				'name' => 'h6_font_size_desktop',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d2affa1c758',
				'label' => 'H6 Font Size (Mobile)',
				'name' => 'h6_font_size_mobile',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_63d295daf2e64',
				'label' => 'H6 Style',
				'name' => 'h6_style',
				'aria-label' => '',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'normal' => 'normal',
					'italic' => 'italic',
				),
				'default_value' => false,
				'return_format' => 'value',
				'multiple' => 0,
				'allow_null' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62e7b02d7eb53',
				'label' => 'H6 Colour',
				'name' => 'h6_colour',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-typography',
				),
			),
		),
		'menu_order' => 3,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	endif;

	if ( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_62e7b4af3e517',
		'title' => 'Social',
		'fields' => array(
			array(
				'key' => 'field_62e7b4b6c9b7d',
				'label' => 'Platforms',
				'name' => 'platforms',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_62e7b4d8c9b7e',
						'label' => 'Name',
						'name' => 'name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_62e7b4b6c9b7d',
					),
					array(
						'key' => 'field_62e7b4edc9b7f',
						'label' => 'Icon',
						'name' => 'icon',
						'aria-label' => '',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'parent_repeater' => 'field_62e7b4b6c9b7d',
					),
					array(
						'key' => 'field_62e7b510c9b80',
						'label' => 'Link',
						'name' => 'link',
						'aria-label' => '',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'parent_repeater' => 'field_62e7b4b6c9b7d',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'theme-general-settings',
				),
			),
		),
		'menu_order' => 4,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	endif;

				if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_63d27efc46234',
	'title' => 'Import Fonts',
	'fields' => array(
		array(
			'key' => 'field_63d27efc87105',
			'label' => 'Google Font',
			'name' => 'google_font',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Copy and paste the entire embed code (in <link> tags) from https://fonts.google.com/specimen/FONT_NAME',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_63d27fd387106',
			'label' => 'Adobe Typekit',
			'name' => 'typekit',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Copy and paste the Project ID from the kit you wish to use on https://fonts.adobe.com/my_fonts#web_projects-section (login required)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-typography',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;		
	
}

add_action('acf/init', 'my_acf_add_local_field_groups');



function adobe_google(){

	if( get_field('field_63d27fd387106', 'option') ): ?>
		<link rel="stylesheet" href="https://use.typekit.net/<?php the_field('field_63d27fd387106', 'option'); ?>.css">
		<script type="text/javascript">console.log('typekit')</script>
	<?php endif; ?>

	<?php if( get_field('field_63d27efc87105', 'option') ): ?>
		<?php the_field('field_63d27efc87105', 'option'); ?>
		<script type="text/javascript">console.log('google-font')</script>
	<?php endif; 

};

add_action('wp_head', 'adobe_google');


